env:
  BUILDKITE_ARTIFACT_PATHS: tmp/logs/*.log
  BUILDKITE_GIT_CLEAN_FLAGS: -fq
  LC_ALL: pt_BR.UTF-8
  LANG: pt_BR.UTF-8
  BETA_TESTERS: product,dev
  ALPHA_TESTERS: dev

steps:
- label: 'test'
  command:
  - .buildkite/run setup
  - yarn test
- wait
- label: 'build:ios'
  command:
  - .buildkite/run ios setup,assets,bump,build
  - (cd ios/build && zip -qr EmCasa.xcarchive.zip EmCasa.xcarchive)
  - buildkite-agent artifact upload "ios/build/EmCasa.xcarchive.zip"
  - buildkite-agent artifact upload "ios/build/EmCasa.xcarchive/Info.plist"
- label: 'build:android'
  command:
  - .buildkite/run android setup,assets,bump,build
  - (cd android/app && zip -qr build.zip build)
  - buildkite-agent artifact upload "android/app/build.zip"
- wait
- label: 'beta:ios'
  command:
  - buildkite-agent artifact download "ios/build/EmCasa.xcarchive.zip" . --step "build:ios"
  - (cd ios/build && unzip -q EmCasa.xcarchive.zip)
  - buildkite-agent artifact download "ios/build/EmCasa.xcarchive/Info.plist" . --step "build:ios"
  - .buildkite/run ios setup,sign,deploy --profile beta
- label: 'beta:android'
  command:
  - buildkite-agent artifact download "android/app/build.zip" . --step "build:android"
  - (cd android/app && unzip -q build.zip build/outputs/apk/app-release.apk)
  - .buildkite/run setup
  - .buildkite/run android deploy --profile beta
- block: ":rocket: Release"
- label: "release:android"
  command:
  - buildkite-agent artifact download "android/app/build.zip" . --step "build:android"
  - (cd android/app && unzip -q build.zip)
  - .buildkite/run android setup,bump,deploy --profile production
- label: 'release:ios'
  command:
  - buildkite-agent artifact download "ios/build/EmCasa.xcarchive.zip" . --step "build:ios"
  - (cd ios/build && unzip -q EmCasa.xcarchive.zip)
  - buildkite-agent artifact download "ios/build/EmCasa.xcarchive/Info.plist" . --step "build:ios"
  - .buildkite/run ios setup,sign,deploy --profile production
