#!/bin/bash

export ROOT=${BUILDKITE_BUILD_CHECKOUT_PATH:-$PWD}
export PATH=$PATH:$ROOT/node_modules/.bin

if [[ "$1" =~ ^(android|ios)$ ]]; then PLATFORM=$1; shift; fi
if [[ "$1" =~ ^[a-z,]+$ ]]; then SCRIPTS=$1; shift;
else echo "Invalid script $1"; exit 1; fi

for script in $(echo $SCRIPTS | sed -e "s/\([^,]*\)/\1,$PLATFORM\/\1/g" | tr "," " "); do
  if [[ -f $ROOT/.buildkite/$script.sh ]]; then
    source $ROOT/.buildkite/$script.sh $@
  fi
done
