# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'EmCasa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'EmCasaTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
