# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ANDROID_DIR = File.expand_path('../android', __dir__)
IOS_DIR = File.expand_path('../ios', __dir__)

def package
  $package_json ||= JSON.parse(
    File.read('../package.json'),
    symbolize_names: true
  )
end

platform :android do
  BUILD_NUMBER_PATTERN = '(versionCode) ([[:digit:]]*)'
  VERSION_NAME_PATTERN = '(versionName) "(.*)"'

  desc "Bump build and version numbers"
  lane :bump do |build_number: nil, version: nil|
    gradle_build = "#{ANDROID_DIR}/app/build.gradle"
    version ||= package[:version]
    unless build_number
      build_number = sh "awk 'match($0,/#{BUILD_NUMBER_PATTERN}/) {print $2}' #{gradle_build}"
      build_number = build_number.to_i + 1
    end
    # Set extended regex option according to OS
    # http://www.grymoire.com/Unix/Sed.html#uh-4a
    opt = case RUBY_PLATFORM
      when /darwin/i then 'E'
      when /linux|arch/i then 'r'
    end
    sh %Q{sed -#{opt}i '' 's/#{BUILD_NUMBER_PATTERN}/\\1 #{build_number}/' #{gradle_build}}
    sh %Q{sed -#{opt}i '' 's/#{VERSION_NAME_PATTERN}/\\1 "#{version}"/' #{gradle_build}}
  end

  desc "Build akp"
  lane :build do |options|
    bump options
    gradle(task: "clean assembleRelease", project_dir: ANDROID_DIR)
  end
end

platform :ios do
  PROJECT_DIR="#{IOS_DIR}/EmCasa.xcodeproj"

  desc "Bump build and version numbers"
  lane :bump do |build_number: nil, version: nil|
    version ||= package[:version]
    increment_build_number(build_number: build_number, xcodeproj: PROJECT_DIR)
    increment_version_number(version_number: version, xcodeproj: PROJECT_DIR)
  end

  lane :build do |options|
    bump options
    gym(scheme: 'EmCasa', project: IOS_DIR)
  end
end

